access:
  repo_plugins:
    xxx/xxx: # The Gitee org/repo
    - welcome    
  plugins:
    # - name: approve
      # endpoint: http://192.168.1.195:8889/gitee-hook
      # events:
        # - "Note Hook"
        # - "Issue Hook"
        # - "Merge Request Hook"
     - name: welcome
       endpoint: http://localhost:8888/gitee-hook
       events:
         - "Note Hook"
         - "Issue Hook"
         - "Merge Request Hook"
         - "Push Hook"
    # - name: associate
      # endpoint: http://192.168.1.195:8899/gitee-hook
      # events:
        # - "Note Hook"
        # - "Issue Hook"
        # - "Merge Request Hook"
